import Footer from "@/components/custom/footer";
import Header from "@/components/custom/Header";
import Link from "next/link";
import { FaArrowLeft } from "react-icons/fa";

export default function Policity() {
    return (
        <div>
            <main className="relative overflow-x-hidden z-10 w-full max-w-[1400px] mx-auto px-6 pt-[100px] flex-grow">
                <div className="absolute sm:top-[30px] top-[70px] left-1/2 -translate-x-1/2 w-[140vw] max-w-[1600px] sm:h-[900px] h-[600px] bg-[url('/images/mainbg.svg')] bg-no-repeat bg-cover bg-bottom sm:bg-top z-0 pointer-events-none sm:rotate-[35deg] rotate-[200deg]" />
                <Header />
                <div>
                    <div className="flex sm:justify-start justify-center mb-[46px] items-center gap-[5px] mt-[50px]">
                        <Link href={"/"} className="flex items-center gap-[4px] text-[rgba(80,80,80,1)]">
                            <FaArrowLeft className="text-[rgba(80,80,80,1)] !w-3 !h-3" />
                            Главная
                        </Link>
                        <span className="text-[rgba(80,80,80,1)] font-bold">- Политика конфиденциальности</span>
                    </div>
                    <div>
                        <h3 className="sm:text-[60px] text-[24px] text-center sm:text-left uppercase font-[400] sm:mb-[46px] mb-[24px]">
                            Политика конфиденциальности
                        </h3>
                    </div>
                    <div className="relative bg-[rgba(255,255,255,1)] border-[2px] border-[rgba(0,0,0,0.05)] p-[35px] rounded-[20px] mb-[43px]">
                        <div className="absolute w-[192px] h-[8px] top-0 left-[35px] bg-[rgba(229,9,9,1)] rounded-b-[4px]"></div>
                        <h3 className="text-[24px] font-[600] mb-[20px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h3>
                        <p className="text-[16px]">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce venenatis fermentum erat id faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi aliquet posuere nisl eu imperdiet. Duis consequat neque a dignissim commodo. Vivamus in nunc aliquet, venenatis turpis in, bibendum odio. Quisque tristique dui ut lacus dignissim dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam eget posuere metus. Fusce quis lacus neque.
                            Morbi feugiat arcu vel est convallis molestie. Nam interdum urna nec massa malesuada, vel iaculis ligula molestie. Mauris aliquet commodo consectetur. Donec volutpat efficitur erat sit amet vehicula. Ut semper lectus magna, eu tempus dui laoreet non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis scelerisque ex arcu, quis lacinia ex dapibus a. In quis tellus non nisl vestibulum tempus eget vel nibh. Curabitur tempor augue lorem, egestas aliquet ligula dapibus sed. Aliquam erat volutpat. Proin vulputate diam libero, ultricies pellentesque felis faucibus ut. Nulla molestie molestie posuere. Pellentesque nec tellus auctor elit euismod mattis. Morbi at odio dolor.
                            Donec viverra facilisis ex, ut suscipit purus dapibus nec. Etiam sed mauris aliquet, sodales turpis in, laoreet purus. Aliquam vitae euismod nisl. Vestibulum sed blandit sem. Sed auctor consequat tincidunt. Praesent libero est, euismod at mollis sagittis, elementum aliquam purus. Nulla ut urna sed lorem mollis sagittis quis nec ipsum. Nulla dignissim quis tellus tempor blandit. Nullam tincidunt urna quis orci aliquam, a sagittis enim semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
                            In porttitor scelerisque risus ac dignissim. Vivamus felis massa, rhoncus ut convallis eget, elementum nec quam. Mauris porttitor nunc a lacus lobortis, vitae gravida ante molestie. Suspendisse scelerisque sed arcu vel commodo. Vestibulum lobortis eu leo sed tincidunt. Maecenas lacus est, viverra vel auctor ut, lacinia et arcu. Nulla vehicula id enim in dignissim. Fusce sodales consectetur aliquam. Duis vehicula tellus ante, sollicitudin malesuada neque blandit vel. Morbi eu diam fermentum, tincidunt justo a, elementum enim. Suspendisse rutrum est a interdum convallis. Quisque vel eros aliquet neque tristique hendrerit non in justo. In facilisis mattis justo, in consequat augue posuere in. Morbi lobortis, arcu sed interdum eleifend, nibh lectus eleifend lectus, eleifend pharetra metus tortor vitae ante.
                            Pellentesque odio enim, scelerisque at scelerisque non, gravida a turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean sit amet sodales neque, in interdum lorem. Pellentesque tristique augue augue. Integer efficitur, leo et imperdiet efficitur, neque magna posuere eros, sed mollis nulla tellus non nibh. Maecenas ut pellentesque lorem, eu mattis neque. Etiam at tellus lectus. Morbi varius, sem eu condimentum cursus, elit nunc hendrerit mi, at ultricies ligula orci ac nibh. Cras a luctus velit, nec elementum mauris. Vivamus libero quam, fermentum nec felis vel, hendrerit ullamcorper urna. Duis tincidunt gravida porttitor.
                            Donec tristique fringilla accumsan. Donec ac nibh mollis purus fringilla pharetra in at sem. Donec at libero euismod, bibendum turpis in, pellentesque urna. Donec vel augue quam. In fermentum condimentum lorem a sodales. Vestibulum a interdum lorem. Ut mauris quam, aliquet vel ligula id, feugiat eleifend turpis. Sed consectetur varius consequat. Maecenas euismod tellus et felis fermentum lacinia. Donec congue, orci vulputate tincidunt fermentum, nibh quam imperdiet nunc, nec convallis mi purus id tellus. Pellentesque consequat dolor quis sem congue aliquet. In hac habitasse platea dictumst. Vivamus vulputate non tellus vel interdum. Nulla sodales tortor ante, finibus semper lectus feugiat et. Donec hendrerit rutrum elit. Quisque consectetur ex turpis, eu ultrices ante sagittis faucibus.
                            Vivamus libero nisi, malesuada id metus non, sagittis molestie est. Nullam magna nibh, faucibus quis volutpat quis, elementum sit amet est. Nunc sodales mauris neque, ut feugiat libero vestibulum ullamcorper. Curabitur feugiat dui pellentesque massa semper suscipit. Proin lacus mi, pellentesque quis dui ut, accumsan tincidunt ante. Etiam enim augue, posuere non arcu vitae, placerat mollis purus. Fusce elementum leo finibus, consectetur ex sed, luctus nisl. Nunc ornare lacinia magna nec condimentum. Proin et nisi urna. Nunc posuere auctor varius. Mauris ullamcorper auctor nisl.
                            Integer ut nisi ex. Aliquam mattis augue eros, ut commodo elit cursus id. Suspendisse posuere ex at sem pretium cursus. Praesent dictum vehicula molestie. Praesent finibus risus ut aliquet tincidunt. Suspendisse ac sem fermentum, consectetur lacus ac, posuere augue. Vestibulum sagittis pharetra quam, sit amet accumsan justo semper nec. Praesent vel consequat massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla laoreet porta tortor, a pharetra eros ultricies a. Praesent sapien eros, eleifend a elit non, finibus rhoncus erat. Suspendisse eu quam erat. Fusce eu interdum arcu. Etiam sed lacus eget ex feugiat volutpat sit amet ac tellus.
                            Mauris quis risus venenatis diam tincidunt posuere. Donec bibendum ex ut cursus tempor. Aliquam erat volutpat. Fusce commodo pretium neque eu elementum. Nam pharetra eros eget dolor faucibus, id volutpat quam dictum. Integer sapien massa, interdum cursus urna id, semper ultricies nunc. Curabitur vulputate tortor dapibus dolor malesuada laoreet. Etiam blandit ut justo a feugiat. Praesent sit amet nisl sagittis, convallis ex et, consequat neque. Quisque ac congue purus, sit amet tincidunt erat. Maecenas sodales dui convallis malesuada dapibus. Morbi non placerat risus, vitae suscipit tellus. Duis vel massa rhoncus, lacinia arcu ac, placerat felis. Donec egestas libero vel tempor volutpat. Donec lobortis fermentum ipsum vitae ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
                            Suspendisse eget ligula mollis nisi feugiat maximus. In lacus urna, interdum eu bibendum nec, aliquet eget nibh. Nunc molestie nibh quam, at bibendum turpis dignissim sit amet. Sed cursus magna sed nunc egestas, viverra egestas est euismod. Fusce sit amet fermentum urna, ut mattis ante. Phasellus et dictum velit. Proin vulputate tincidunt augue, id sodales nibh finibus interdum. Sed vulputate tortor id volutpat facilisis. Integer quis porttitor purus. Sed tempor augue vitae luctus molestie. Integer eros ex, imperdiet quis ligula ut, posuere scelerisque massa. Phasellus sodales tincidunt auctor. Phasellus auctor nunc id luctus auctor. Morbi cursus vulputate rutrum.
                            Nullam a commodo erat. Aliquam aliquam arcu nec orci aliquam blandit. Aenean at massa pulvinar, maximus elit quis, interdum urna. Curabitur ultricies lacus nunc, eget lobortis risus consectetur malesuada. Duis eleifend dictum neque, quis porta dui rutrum ut. Pellentesque vel hendrerit nisi. Donec vulputate at risus nec mollis.
                            Pellentesque nec accumsan augue. Aliquam arcu sapien, rhoncus tristique cursus et, ullamcorper a nisl. Donec vulputate molestie odio. Duis eget elit odio. Maecenas vitae commodo libero, rutrum egestas orci. Maecenas maximus justo a ornare sagittis. Morbi id scelerisque ipsum. Pellentesque placerat et diam et luctus. Quisque efficitur, dolor id bibendum sagittis, purus neque pharetra enim, eget tristique leo nisi sit amet odio. Praesent posuere mauris nibh, a maximus quam commodo eu. Mauris molestie lacinia odio sit amet egestas.
                            Proin felis diam, viverra non ex a, convallis convallis nisi. Curabitur ex purus, fringilla sit amet est ut, tincidunt condimentum nisi. Phasellus vel dolor at dui eleifend bibendum. Morbi ullamcorper sed tellus ac cursus. Mauris a urna at nulla semper malesuada non semper lectus. Maecenas consectetur ac massa sed commodo. Donec feugiat viverra velit a feugiat. Duis placerat eu sapien quis interdum. Aenean interdum consectetur velit, in sodales diam sagittis sed. Curabitur consectetur quam lacinia lectus accumsan, ac congue magna vehicula.
                            Mauris tincidunt ac tortor ac ultrices. Duis sed dui at mauris aliquet feugiat. Phasellus tempus, erat non pretium interdum, velit risus laoreet ex, nec consectetur est lectus eu sem. Aliquam a risus sapien. Nunc lobortis diam tincidunt risus tincidunt lobortis. Vestibulum placerat sapien eget est mollis pulvinar. Nullam dapibus nisi eu turpis gravida, et mattis urna tempus.
                            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo, ligula in convallis accumsan, ipsum sapien imperdiet ligula, vel fringilla tortor justo vel ligula. Donec et mollis libero. In non vulputate ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras vehicula, nulla sed vestibulum commodo, odio nisl aliquam dolor, ut consequat purus dui ut nisi. Proin imperdiet ut nulla sed maximus.
                        </p>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}